#include <string>
#include <vector>
#include <regex>
#include "make_json.hpp"
#include "file_management.hpp"
#include "uuid_generator.hpp"
#include "item.hpp"
#include "entity.hpp"
#include "manifest.hpp"
#include "obfuscator.hpp"